# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WC8sr__nbabKmV7v5yu3b_PmoDEoI8iL
"""

!pip install pandas --quite

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, learning_curve
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

data=pd.read_csv("/content/StudentsPerformance.csv")

data.head()

data['average_score']=(data['math score']+data['reading score']+data['writing score'])/3

data['Pass_Fail'] = np.where(data['average_score'] >= 50, 1, 0)

data[['average_score','Pass_Fail']].head()

le = LabelEncoder()

categorical = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
]

for col in categorical:
    data[col] = le.fit_transform(data[col])

X = data.drop(['average_score','Pass_Fail'], axis=1)

y = data['Pass_Fail']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train,y_train)

pred_lr = lr.predict(X_test)

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train,y_train)

pred_dt = dt.predict(X_test)

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train,y_train)

pred_rf = rf.predict(X_test)

models = {
    "Logistic Regression": pred_lr,
    "Decision Tree": pred_dt,
    "Random Forest": pred_rf
}

results=[]

for name,pred in models.items():

    results.append([
        name,
        accuracy_score(y_test,pred),
        precision_score(y_test,pred),
        recall_score(y_test,pred),
        f1_score(y_test,pred)
    ])

result_df = pd.DataFrame(results,
                         columns=['Model','Accuracy','Precision','Recall','F1 Score'])

print(result_df)

sns.heatmap(confusion_matrix(y_test,pred_rf),
            annot=True,
            fmt='d',
            cmap='Blues')

plt.title("Random Forest Confusion Matrix")
plt.show()

print(classification_report(y_test,pred_rf))

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

for name,model in models.items():

    score = cross_val_score(model,X,y,cv=5)

    print(name)
    print("Scores:",score)
    print("Average:",score.mean())
    print()

param_dt = {

    'max_depth':[3,5,7,10,None],
    'min_samples_split':[2,5,10],
    'criterion':['gini','entropy']

}

grid_dt = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_dt,
    cv=5
)

grid_dt.fit(X_train,y_train)

print("Best Parameters")
print(grid_dt.best_params_)

print("Best Score")
print(grid_dt.best_score_)

param_rf = {

    'n_estimators':[50,100,200],
    'max_depth':[5,10,None],
    'min_samples_split':[2,5]

}

grid_rf = GridSearchCV(

    RandomForestClassifier(random_state=42),
    param_rf,
    cv=5

)

grid_rf.fit(X_train,y_train)

print(grid_rf.best_params_)
print(grid_rf.best_score_)

train_sizes, train_scores, test_scores = learning_curve(

    RandomForestClassifier(random_state=42),
    X,
    y,
    cv=5

)

train_mean = train_scores.mean(axis=1)
test_mean = test_scores.mean(axis=1)

plt.figure(figsize=(8,5))

plt.plot(train_sizes,train_mean,label='Training Score')
plt.plot(train_sizes,test_mean,label='Validation Score')

plt.xlabel("Training Samples")
plt.ylabel("Accuracy")
plt.title("Learning Curve")

plt.legend()

plt.show()

best_rf = grid_rf.best_estimator_

best_rf.fit(X_train,y_train)

pred = best_rf.predict(X_test)

print(classification_report(y_test,pred))

print("Accuracy:",accuracy_score(y_test,pred))

"""The performance of Logistic Regression, Decision Tree, and Random Forest models was compared using Accuracy, Precision, Recall, and F1-score. Five-fold cross-validation was applied to evaluate model stability. Hyperparameter tuning improved the performance of both Decision Tree and Random Forest models. Among all the models, Random Forest achieved the highest accuracy and F1-score because it combines multiple decision trees, reduces overfitting, and provides better generalization. Therefore, Random Forest was selected as the best-performing model for predicting student pass/fail status."""





