# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vZPIXXr0Q2HBOd6bQK1Rpi7zJoODnqd
"""

!pip install pandas --quite
import pandas as pd

"""Question 1 understanding dataset"""

agri_data=pd.read_csv('/content/agriculture_ml_dataset_cw.csv')

print("number of rows and columns is ")
agri_data.shape

print(f'names of all the columns is {agri_data.info}')

print(f'the first 10 records are {agri_data.head(10)}')

"""Question 2 data types and missing values"""

# to check data type of each column
agri_data.info()

# identify if missing values are present or not
agri_data.isnull().sum()

# mention effected column by missing values
missing=agri_data.isnull().sum()
print(missing[missing>0])

"""Question 3 descriptive statistics"""

# summary stats of all numerical features
num_cols=['Rainfall','Temperature','Humidity','Nitrogen','Yield']
for col in num_cols:
  agri_data[col].fillna(agri_data[col].mean(),inplace=True)

cat_cols = ['Soil_Type','Irrigation','Crop_Type','Season']
for col in cat_cols:
    agri_data[col].fillna(agri_data[col].mode()[0], inplace=True)

std_values = agri_data.std(numeric_only=True)

highest_std_col = std_values.idxmax()
highest_std_value = std_values.max()

print("Column with highest standard deviation:", highest_std_col)
print("Standard deviation:", highest_std_value)

"""PART B Exploratory data analysis"""

# Question 4 distribution analysis

# Commented out IPython magic to ensure Python compatibility.
# histogram for rainfal_mm
!pip install plotly matplotlib seaborn --quiet
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

print(agri_data.columns)

px.histogram(agri_data,x='Rainfall',title='Rainfall')

px.histogram(agri_data,x='Temperature',title='Temperature analysis')

px.histogram(agri_data,x='Fertilizer',title='fertilizers_kg')

px.histogram(agri_data,x='Yield',title='yield_ton_per_hectare')

"""Question 5 crop type analysis"""

# number of recordds for each crop type
crop_counts = agri_data['Crop_Type'].value_counts()
print(crop_counts)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.countplot(data=agri_data, x='Crop_Type')
plt.title('Count of Records by Crop Type')
plt.xlabel('Crop Type')
plt.ylabel('Count')
plt.show()

import plotly.express as px

fig = px.histogram(
    agri_data,
    x='Crop_Type',
    title='Count of Records by Crop Type'
)

fig.show()

most_frequent_crop = agri_data['Crop_Type'].value_counts().idxmax()
count = agri_data['Crop_Type'].value_counts().max()

print("Most frequent crop:", most_frequent_crop)
print("Number of records:", count)

"""Q6. Soil Type Analysis

"""

soil_counts = agri_data['Soil_Type'].value_counts()
print(soil_counts)

import plotly.express as px

fig = px.histogram(
    agri_data,
    x='Soil_Type',
    title='Count of Records by Soil Type'
)

fig.show()

print(agri_data['Soil_Type'].value_counts())
print("\nMost common soil type:", agri_data['Soil_Type'].mode()[0])

"""Q7. Yield Distribution"""

import plotly.express as px

fig = px.histogram(
    agri_data,
    x='Yield',
    nbins=20,
    title='Distribution of Yield'
)

fig.show()

"""since , the graph is bell shaped The yield distribution appears approximately normal, with most values concentrated around the mean. No significant outliers are visible.

Q8. Scatter Plot Analysis
"""

# scatter plot of rainfall_mm vs yield_ton_per_hectare
import plotly.express as px

fig = px.scatter(
    agri_data,
    x='Rainfall',
    y='Yield',
    title='Rainfall vs Yield',
    labels={
        'Rainfall': 'Rainfall (mm)',
        'Yield': 'Yield (ton/hectare)'
    }
)

fig.show()

fig = px.scatter(
    agri_data,
    x='Fertilizer',
    y='Yield',
    title='Fertilizer vs Yield',
    labels={
        'Fertilizer': 'Fertilizer (kg)',
        'Yield': 'Yield (ton/hectare)'
    }
)

fig.show()

print(agri_data.dtypes)

agri_data['Fertilizer'] = pd.to_numeric(agri_data['Fertilizer'], errors='coerce')

print(agri_data[['Fertilizer', 'Yield']].isnull().sum())

agri_data['Fertilizer'] = pd.to_numeric(agri_data['Fertilizer'], errors='coerce')

print(
    agri_data[['Fertilizer','Yield']].dropna()
    .corr()
)

"""Q9. Correlation Analysis"""

corr_matrix = agri_data.corr(numeric_only=True)
print(corr_matrix)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', linewidths=0.5)

plt.title('Correlation Heatmap')
plt.show()

yield_corr = corr_matrix['Yield'].sort_values(ascending=False)

print(yield_corr)

top3_features = yield_corr.drop('Yield').head(3)

print("Top 3 features correlated with Yield:")
print(top3_features)

"""Q10. Group-Based Analysis"""

crop_avg_yield = agri_data.groupby('Crop_Type')['Yield'].mean()
print(crop_avg_yield)

soil_avg_yield = agri_data.groupby('Soil_Type')['Yield'].mean()
print(soil_avg_yield)

highest_yield_crop = crop_avg_yield.idxmax()
highest_crop_value = crop_avg_yield.max()

print("Crop with highest average yield:", highest_yield_crop)
print("Average yield:", highest_crop_value)

highest_yield_soil = soil_avg_yield.idxmax()
highest_soil_value = soil_avg_yield.max()

print("Soil type with highest average yield:", highest_yield_soil)
print("Average yield:", highest_soil_value)

"""Part C: Data Preparation
Q11. Feature Encoding
"""

categorical_cols = agri_data.select_dtypes(include=['object']).columns
print("Categorical Columns:")
print(categorical_cols)

agri_encoded = pd.get_dummies(agri_data, columns=categorical_cols, drop_first=True)

print(agri_encoded.head())

print(agri_encoded.columns)
print(agri_encoded.shape)

"""Q12. Feature Selection

"""

X = agri_data.drop('Yield', axis=1)
y = agri_data['Yield']

print("X shape:", X.shape)
print("y shape:", y.shape)

"""Part D: Machine Learning
Q13. Train-Test Split
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""Q14. Linear Regression Model"""

agri_encoded = pd.get_dummies(agri_data, drop_first=True)

from sklearn.model_selection import train_test_split

X = agri_encoded.drop('Yield', axis=1)
y = agri_encoded['Yield']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

import pandas as pd

coefficients = pd.Series(model.coef_, index=X.columns)

print("Intercept:", model.intercept_)
print("\nCoefficients:\n", coefficients)

print("Highest positive feature:")
print(coefficients.idxmax(), coefficients.max())



